# Задание 1
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
  - оценка 2 и меньше - низкий рейтинг
  - оценка 4 и меньше - средний рейтинг
  - оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [1]:
import pandas as pd

def new_rating(rate):
    if rate <= 2:
        return 'low'
    elif rate <= 4:
        return 'medium'
    else:
        return 'hight'

rating = pd.read_csv('ratings.csv')
rating['rating_category'] = rating['rating'].apply(new_rating)
rating.sample(25)

       userId  movieId  rating   timestamp rating_category
32205     220     8665     4.0  1230060248          medium
81243     514     2458     2.0  1533873657             low
92678     599      144     2.5  1519343783          medium
89318     580       10     3.5  1167792602          medium
81285     514     3363     4.5  1533948798           hight
28578     199       47     3.0   940372883          medium
2422       19      761     3.0   965709832          medium
13338      84     1288     4.0   860397323          medium
533         5      296     5.0   847434748           hight
68779     448      870     1.0  1034616569             low
56677     377      926     4.5  1340343456           hight
17276     111      500     4.0  1516156095          medium
22702     156      185     3.0  1106853925          medium
17222     110     1193     4.0  1175330077          medium
18374     117      110     5.0   844162850           hight
42149     288      273     2.0   976124938             low
42024     287     2174     4.0  1110229938          medium
34077     232     4069     3.0  1218166738          medium
47988     310     7261     3.5  1078649414          medium
95467     600     2416     2.0  1237711731             low
99266     608     4545     2.5  1117506922          medium
65472     420     1161     3.5  1218206918          medium
96479     603     1513     3.0   953926273          medium
13956      89   128852     4.5  1520409173           hight
81462     514   179401     4.0  1533947052          medium

# Задание 2
Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце 'region' пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим 'undefined'.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:
```
geo_data = {

    'Центр': ['москва', 'тула', 'ярославль'],

    'Северо-Запад': ['петербург', 'псков', 'мурманск'],

    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']

}
```
Результат классификации запишите в отдельный столбец region.

In [2]:
def region(data):
    for region in geo_data:
        for city in geo_data[region]:
            if city in data:
                return region
    return 'undefined'

geo_data = {'Центр': ['москва', 'тула', 'ярославль'],
           'Северо-Запад': ['петербург', 'псков', 'мурманск'],
           'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']}

keywords = pd.read_csv('keywords.csv')
keywords['region'] = keywords['keyword'].apply(region)
keywords.region.value_counts()

undefined         99253
Центр               387
Северо-Запад        266
Дальний Восток       94
Name: region, dtype: int64

# Задание 3 (бонусное)
Есть мнение, что "раньше снимали настоящее кино, не то что сейчас". Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

1. В переменную years запишите список из всех годов с 1950 по 2010.

2. Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:
  - для каждой строки пройдите по всем годам списка years
  - если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
  - если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год

3. Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец 'year'

4. Посчитайте средний рейтинг всех фильмов для каждого значения столбца 'year' и отсортируйте результат по убыванию рейтинга