# Задание 1
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
  - оценка 2 и меньше - низкий рейтинг
  - оценка 4 и меньше - средний рейтинг
  - оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [1]:
import pandas as pd

def new_rating(rate):
    if rate <= 2:
        return 'low'
    elif rate <= 4:
        return 'average'
    else:
        return 'high'

rating = pd.read_csv('ratings.csv')
rating['rating_category'] = rating['rating'].apply(new_rating)
rating.sample(25)

       userId  movieId  rating   timestamp rating_category
44510     297     1037     2.0   900876328             low
58139     381      589     2.5  1164877216         average
45869     304     1393     3.0   881428397         average
61445     405     1233     4.5  1295922950            high
75619     477     2019     4.5  1200939375            high
97134     604      606     3.0   832080615         average
47328     307     5312     2.0  1186173238             low
82072     520     2657     2.5  1326610935         average
29420     202      457     3.0   974918472         average
10249      66     5418     5.0  1093748020            high
43097     288    36509     2.5  1216994285         average
55352     367     3824     1.0   997813277             low
35422     239     2405     3.5  1221147400         average
16399     105     4874     5.0  1446749868            high
53687     354     2324     4.5  1200870723            high
48756     316     1676     2.5  1111493445         average
87632     564    88812     3.5  1481817663         average
70401     448   137517     0.5  1492953436             low
67464     437       14     3.0   859721080         average
22856     156     1589     3.0  1106854059         average
52530     343      527     5.0  1202061421            high
57820     380    68157     3.0  1493420409         average
80670     509    53322     3.0  1435994136         average
53022     350       65     3.0   864941118         average
32799     222    87869     2.0  1391349147             low

# Задание 2
Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце 'region' пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим 'undefined'.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:
```
geo_data = {

    'Центр': ['москва', 'тула', 'ярославль'],

    'Северо-Запад': ['петербург', 'псков', 'мурманск'],

    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']

}
```
Результат классификации запишите в отдельный столбец region.

In [2]:
def region(data):
    for region in geo_data:
        for city in geo_data[region]:
            if city in data:
                return region
    return 'undefined'

geo_data = {'Центр': ['москва', 'тула', 'ярославль'],
           'Северо-Запад': ['петербург', 'псков', 'мурманск'],
           'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']}

keywords = pd.read_csv('keywords.csv')
keywords['region'] = keywords['keyword'].apply(region)
keywords.region.value_counts()

undefined         99253
Центр               387
Северо-Запад        266
Дальний Восток       94
Name: region, dtype: int64

# Задание 3 (бонусное)
Есть мнение, что "раньше снимали настоящее кино, не то что сейчас". Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

1. В переменную years запишите список из всех годов с 1950 по 2010.

2. Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:
  - для каждой строки пройдите по всем годам списка years
  - если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
  - если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год

3. Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец 'year'

4. Посчитайте средний рейтинг всех фильмов для каждого значения столбца 'year' и отсортируйте результат по убыванию рейтинга